export default [
  { name: "Afegane", code: "AFN" },
  { name: "Ariary Malgaxe", code: "MGA" },
  { name: "Baht Tailandês", code: "THB" },
  { name: "Balboa Panamenho", code: "PAB" },
  { name: "Birr Etíope", code: "ETB" },
  { name: "Bolívar Venezuelano", code: "VES" },
  { name: "Boliviano", code: "BOB" },
  { name: "Cedi Ganês", code: "GHS" },
  { name: "Colón Costarriquenho", code: "CRC" },
  { name: "Córdoba Nicaraguense", code: "NIO" },
  { name: "Dalasi Gambiano", code: "GMD" },
  { name: "Dinar Bahreinita", code: "BHD" },
  { name: "Dinar Iraquiano", code: "IQD" },
  { name: "Dinar Jordaniano", code: "JOD" },
  { name: "Dinar Kuwaitiano", code: "KWD" },
  { name: "Dinar Líbio", code: "LYD" },
  { name: "Dinar Sérvio", code: "RSD" },
  { name: "Dinar Tunisiano", code: "TND" },
  { name: "Dirham dos Emirados", code: "AED" },
  { name: "Dobra São Tomense", code: "STN" },
  { name: "Dólar Americano", code: "USD" },
  { name: "Dólar Australiano", code: "AUD" },
  { name: "Dólar Canadense", code: "CAD" },
  { name: "Dólar Neozelandês", code: "NZD" },
  { name: "Dong Vietnamita", code: "VND" },
  { name: "Dram Armênio", code: "AMD" },
  { name: "Euro", code: "EUR" },
  { name: "Florim Arubano", code: "AWG" },
  { name: "Forint Húngaro", code: "HUF" },
  { name: "Franco CFA (África Central)", code: "XAF" },
  { name: "Franco CFA (África Ocidental)", code: "XOF" },
  { name: "Franco Suíço", code: "CHF" },
  { name: "Gourde Haitiano", code: "HTG" },
  { name: "Guarani Paraguaio", code: "PYG" },
  { name: "Hryvnia Ucraniana", code: "UAH" },
  { name: "Iene Japonês", code: "JPY" },
  { name: "Kina Papua Nova Guiné", code: "PGK" },
  { name: "Kip Laosiano", code: "LAK" },
  { name: "Kuna Croata", code: "HRK" },
  { name: "Kwacha Malauiano", code: "MWK" },
  { name: "Kwacha Zambiano", code: "ZMW" },
  { name: "Kwanza Angolano", code: "AOA" },
  { name: "Kyat Birmanês", code: "MMK" },
  { name: "Lari Georgiano", code: "GEL" },
  { name: "Lempira Hondurenha", code: "HNL" },
  { name: "Leone de Serra Leoa", code: "SLL" },
  { name: "Lira Turca", code: "TRY" },
  { name: "Loti do Lesoto", code: "LSL" },
  { name: "Manat do Azerbaijão", code: "AZN" },
  { name: "Manat do Turcomenistão", code: "TMT" },
  { name: "Metical Moçambicano", code: "MZN" },
  { name: "Naira Nigeriana", code: "NGN" },
  { name: "Nakfa da Eritreia", code: "ERN" },
  { name: "Ngultrum do Butão", code: "BTN" },
  { name: "Ouguiya Mauritânia", code: "MRU" },
  { name: "Pataca de Macau", code: "MOP" },
  { name: "Peso Argentino", code: "ARS" },
  { name: "Peso Chileno", code: "CLP" },
  { name: "Peso Colombiano", code: "COP" },
  { name: "Peso Cubano", code: "CUP" },
  { name: "Peso Dominicano", code: "DOP" },
  { name: "Peso Mexicano", code: "MXN" },
  { name: "Peso Filipino", code: "PHP" },
  { name: "Peso Uruguaio", code: "UYU" },
  { name: "Pula do Botswana", code: "BWP" },
  { name: "Quetzal da Guatemala", code: "GTQ" },
  { name: "Rand Sul-Africano", code: "ZAR" },
  { name: "Real Brasileiro", code: "BRL" },
  { name: "Rial Omani", code: "OMR" },
  { name: "Rial Qatar", code: "QAR" },
  { name: "Rial Iemenita", code: "YER" },
  { name: "Rial Iraniano", code: "IRR" },
  { name: "Riyal Saudita", code: "SAR" },
  { name: "Rublo Russo", code: "RUB" },
  { name: "Rublo Bielorrusso", code: "BYN" },
  { name: "Rufiyaa das Maldivas", code: "MVR" },
  { name: "Rupia Indiana", code: "INR" },
  { name: "Rupia Indonésia", code: "IDR" },
  { name: "Rupia do Sri Lanka", code: "LKR" },
  { name: "Rupia Maurícia", code: "MUR" },
  { name: "Rupia Nepalesa", code: "NPR" },
  { name: "Rupia Paquistanesa", code: "PKR" },
  { name: "Rupia de Seicheles", code: "SCR" },
  { name: "Shilling Queniano", code: "KES" },
  { name: "Shilling Somaliano", code: "SOS" },
  { name: "Shilling Tanzaniano", code: "TZS" },
  { name: "Shilling Ugandês", code: "UGX" },
  { name: "Sol Peruano", code: "PEN" },
  { name: "Som Quirguistão", code: "KGS" },
  { name: "Somoni Tajiquistão", code: "TJS" },
  { name: "Taka Bangladesh", code: "BDT" },
  { name: "Tala de Samoa", code: "WST" },
  { name: "Tenge Cazaquistão", code: "KZT" },
  { name: "Tugrik Mongólia", code: "MNT" },
  { name: "Vatu Vanuatu", code: "VUV" },
  { name: "Won Sul-coreano", code: "KRW" },
  { name: "Yuan Chinês", code: "CNY" },
  { name: "Zloty Polonês", code: "PLN" }
];
